// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGPH9CWoqfZsTGvn2mTJsZVwhRaDxR7AA',
    appId: '1:253857880082:web:50d27695a1a070e7fee0cb',
    messagingSenderId: '253857880082',
    projectId: 'restaurant-app-d6c93',
    authDomain: 'restaurant-app-d6c93.firebaseapp.com',
    storageBucket: 'restaurant-app-d6c93.appspot.com',
    measurementId: 'G-7ZBKHG52YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwExZ54J2zs7UzQXMmqPihUXGOY34ZEZ0',
    appId: '1:253857880082:android:6fd469b88501a615fee0cb',
    messagingSenderId: '253857880082',
    projectId: 'restaurant-app-d6c93',
    storageBucket: 'restaurant-app-d6c93.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmLLD64xPrxYsqujeVFaSVDmi2b2uh1P0',
    appId: '1:253857880082:ios:5e0ca8d200af7cedfee0cb',
    messagingSenderId: '253857880082',
    projectId: 'restaurant-app-d6c93',
    storageBucket: 'restaurant-app-d6c93.appspot.com',
    iosClientId: '253857880082-3e0cq73v2477dqi7mhjs42tjuddl5i5g.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmLLD64xPrxYsqujeVFaSVDmi2b2uh1P0',
    appId: '1:253857880082:ios:e805527ae9cfa59ffee0cb',
    messagingSenderId: '253857880082',
    projectId: 'restaurant-app-d6c93',
    storageBucket: 'restaurant-app-d6c93.appspot.com',
    iosClientId: '253857880082-qc05u8ts7ss0rd2863r39m4qokq58p8a.apps.googleusercontent.com',
    iosBundleId: 'com.example.restaurantApp.RunnerTests',
  );
}
